### ISSUE TITLE
Add info fetching

### ISSUE THREAD

**Issue by ivaylo-iliev-akelius** [ranapat/instancefactory#10]
Would be great if runtime statistics can be shown.

Example info can include:

- number of instances
- list of all instances (???)
- memory of all instances / total memory
- memory for each of the instances (???)
- dependency graph (which instance depends on which) (???)

**Comment by ranapat** [comment]
Memory of each instance needs external libraries - it will make things more complicated.
And adding static jars inside is not nice also.

Dependency graph is similar - the runtime dependencies need reflections and you cannot even catch the runtime local scoped ones.

So for now will leave those out.
